---
CkbNodeRpc: 'http://127.0.0.1:8114'
CkbNodeIndexer: 'http://127.0.0.1:8114'
CkbOfficialNodeRpc: ''
CkbWsUrl: 'ws://127.0.0.1:28114'
LarkApiKey: ''

Loglevel: 'info'
Env: ''

# Define the servers and its IP address, mainly used for making notification much more readable in lark.
Servers: {}

# Transaction fee used for creating and updating cells.
Fee:
  create: 30000
  update: 30000

Notification:
  # Unit: block
  maxTolerableBehindBlock: 3
  # Unit: second
  newBlockNotifyLimit: 120
  # Unit: second
  newBlockWarnLimit: 360

CellDeps:
# The type script used by IndexStateCell.
IndexStateTypeScript:
# The type script used by TimeCell, HeightCell and QuoteCell.
InfoTypeScript:
Timestamp:
Blocknumber:
Quote:
